name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 21
          cache: sbt

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          aws-region: eu-west-1

      - name: Build and Test
        run: |
          sbt compile test assembly
        working-directory: ${{ github.workspace }}

      - name: Copy jar to root
        run: |
          cp archive/target/scala-*/football-time-machine-archive.jar .
          cp api/target/scala-*/football-time-machine-api.jar .

      - uses: guardian/actions-riff-raff@v2
        with:
          configPath: riff-raff.yaml
          projectName: football-time-machine
          buildNumberOffset: 90
          contentDirectories: |
            football-time-machine-archive:
              - football-time-machine-archive.jar
            football-time-machine-api:
              - football-time-machine-api.jar
            football-time-machine:
              - cfn.yaml
